### ISSUE TITLE
Some profiles are not available

### ISSUE THREAD

**Issue by Li-Chunyu043** [oppo-us-research/USST#4]
Hi, thank you for sharing your nice work!

I would like to test and try some of my ideas, however, I found that when training a model on H2O dataset, some files like usst_vit_3d.yml and usst_vit_2d were missing in the config/h2o folder, so I have no Idea...
Is it possible to share the files?

Thanks in advance.

**Comment by Cogito2012** [comment]
@Li-Chunyu043 Thanks for your interest in this work. 

Actually, I haven't implemented the vit versions of the model on the h2o dataset. You may do this by using the following configurations to replace the corresponding items of res18 versions.

```yaml
MODEL:
  backbone: vit/b16-224
  freeze_backbone: True
  vpt: # visual prompt tuning
    prompt_len: 10
    prompt_dim: 768
    dropout: 0.0
```

Optionally, you may also modify the `batch_size` or `snapshot_prefix`.
